### ISSUE TITLE
I am getting this Issue Notes Plugin not working. I am using the same system that i want to scan MACBook PRo m1 max.

### ISSUE THREAD

**Issue by qasimraheem** [ydkhatri/mac_apt#104]
### I am getting this Issue Notes Plugin not working. I am using the same system that i want to scan MACBook PRo m1 max.

I have installed using ./mac_apt_Install_macOS-v23.sh (shell script) using python3.10

`python3 mac_apt.py MOUNTED / NOTES -o ~/Documents/Projects/mac_apt/mac_apt/output -x -c`

```
Output path was : /Users/rakoon/Documents/Projects/mac_apt/mac_apt/output
MAIN-INFO-Started macOS Artifact Parsing Tool, version 1.6.2.dev (20230617)
MAIN-INFO-Dates and times are in UTC unless the specific artifact being parsed saves it as local time!
MAIN-INFO-Python version = 3.10.11 (v3.10.11:7d4cc5aa85, Apr  4 2023, 19:05:19) [Clang 13.0.0 (clang-1300.0.29.30)]
MAIN-INFO-Pytsk  version = 20221228
MAIN-INFO-Pyewf  version = 20230212
MAIN-INFO-Pyvmdk version = 20221124
MAIN-INFO-PyAFF4 version = 0.31
MAIN-INFO-Found valid OSX/macOS kernel
MAIN.HELPERS.MACINFO-INFO-macOS version detected is: Ventura (13.4) Build=22F66
MAIN.HELPERS.MACINFO-ERROR-
Traceback (most recent call last):
  File "/Users/rakoon/Documents/Projects/mac_apt/mac_apt/plugins/helpers/macinfo.py", line 1450, in ListItemsInFolder
    dir = os.listdir(mounted_path)
PermissionError: [Errno 13] Permission denied: '/private/var/db/dslocal/nodes/Default/users'
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=277 GID=277
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=88 GID=88
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=257 GID=257
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=262 GID=262
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=205 GID=205
MAIN.HELPERS.MACINFO-WARNING-There is already a value in DARWIN_USER_DIR /private/var/folders/v1/ffk9cwg51f13jhrh6qh4wtsw0000gn/0
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=269 GID=269
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=89 GID=89
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=240 GID=240
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=274 GID=274
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=87 GID=87
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=268 GID=268
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=24 GID=24
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=202 GID=202
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=259 GID=259
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=65 GID=65
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=282 GID=282
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=213 GID=213
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=266 GID=266
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=263 GID=263
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=242 GID=242
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=258 GID=258
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=265 GID=265
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=270 GID=270
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=26 GID=26
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=248 GID=248
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=55 GID=55
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=289 GID=289
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=200 GID=200
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=241 GID=241
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=441 GID=441
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=261 GID=261
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=278 GID=278
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=273 GID=273
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=212 GID=212
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=222 GID=222
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=235 GID=235
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=1 GID=1
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=260 GID=260
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=247 GID=247
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=4294967294 GID=4294967294
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=92 GID=92
MAIN.HELPERS.MACINFO-WARNING-There is already a value in DARWIN_USER_DIR /private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/0
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=271 GID=271
MAIN-INFO-Opened image /
MAIN-INFO---------------------------------------------------
MAIN-INFO-Running plugin NOTES
MAIN.NOTES-INFO-No notes found
MAIN-INFO---------------------------------------------------
MAIN-INFO-Finished in time = 00:00:00
MAIN-INFO-Review the Log file and report any ERRORs or EXCEPTIONS to the developers
```
<img width="912" alt="Screenshot 2023-07-18 at 6 30 28 PM" src="https://github.com/ydkhatri/mac_apt/assets/35058402/e1edd79a-c314-4b20-9757-a235815b52fb">

**Comment by ydkhatri** [comment]
If you are running on your own local system, then you need to run as root, so just prefix `sudo` to the command and it should run. This is because some of the paths the program references are restricted to root only. 

Another problem here is the order of arguments. The output path and options should be specified first, then the the type of image and its path, then the plugins.

So your command should be 
```
sudo python3 mac_apt.py -o ~/Documents/Projects/mac_apt/mac_apt/output -x -c MOUNTED / NOTES 
```

**Comment by ydkhatri** [comment]
Any updates on this? Did it work now?

**Comment by qasimraheem** [comment]
No it didn't worked, i dont know is i am doing something wrong or there is a bug.
`sudo python3 mac_apt.py MOUNTED / NOTES -o ~/Documents/Projects/mac_apt/mac_apt/output -x -c -p <macbook password>`                                                                                                                                                                                  

Output:
```
Output path was : /Users/rakoon/Documents/Projects/mac_apt/mac_apt/output
MAIN-INFO-Started macOS Artifact Parsing Tool, version 1.6.3.dev (20230720)
MAIN-INFO-Dates and times are in UTC unless the specific artifact being parsed saves it as local time!
MAIN-INFO-Python version = 3.10.11 (v3.10.11:7d4cc5aa85, Apr  4 2023, 19:05:19) [Clang 13.0.0 (clang-1300.0.29.30)]
MAIN-INFO-Pytsk  version = 20221228
MAIN-INFO-Pyewf  version = 20230212
MAIN-INFO-Pyvmdk version = 20221124
MAIN-INFO-PyAFF4 version = 0.31
MAIN-INFO-Found valid OSX/macOS kernel
MAIN.HELPERS.MACINFO-INFO-macOS version detected is: Ventura (13.4) Build=22F66
MAIN.HELPERS.MACINFO-ERROR-Could not find username for UID=4294967294 GID=4294967294
MAIN-INFO-Opened image /
MAIN-INFO---------------------------------------------------
MAIN-INFO-Running plugin NOTES
MAIN.HELPERS.MACINFO-ERROR-Error opening file : /Users/rakoon/Library/Containers/com.apple.Notes/Data/Library/Notes/NotesV7.storedata
Traceback (most recent call last):
  File "/Users/rakoon/Documents/Projects/mac_apt/mac_apt/plugins/helpers/macinfo.py", line 1499, in Open
    file = MountedFile().open(mounted_path, 'rb')
  File "/Users/rakoon/Documents/Projects/mac_apt/mac_apt/plugins/helpers/macinfo.py", line 1267, in open
    self._file  = open(file_path, mode)
PermissionError: [Errno 1] Operation not permitted: '/Users/rakoon/Library/Containers/com.apple.Notes/Data/Library/Notes/NotesV7.storedata'
MAIN.HELPERS.MACINFO-INFO-Failed to export '/Users/rakoon/Library/Containers/com.apple.Notes/Data/Library/Notes/NotesV7.storedata' to '/Users/rakoon/Documents/Projects/mac_apt/mac_apt/output/Export/NOTES/rakoon_NotesV7.storedata'
MAIN.NOTES-INFO-Processing notes for user 'rakoon' from file /Users/rakoon/Library/Containers/com.apple.Notes/Data/Library/Notes/NotesV7.storedata
MAIN.HELPERS.MACINFO-ERROR-Error opening file : /Users/rakoon/Library/Containers/com.apple.Notes/Data/Library/Notes/NotesV7.storedata
Traceback (most recent call last):
  File "/Users/rakoon/Documents/Projects/mac_apt/mac_apt/plugins/helpers/macinfo.py", line 1499, in Open
    file = MountedFile().open(mounted_path, 'rb')
  File "/Users/rakoon/Documents/Projects/mac_apt/mac_apt/plugins/helpers/macinfo.py", line 1267, in open
    self._file  = open(file_path, mode)
PermissionError: [Errno 1] Operation not permitted: '/Users/rakoon/Library/Containers/com.apple.Notes/Data/Library/Notes/NotesV7.storedata'
MAIN.HELPERS.MACINFO-ERROR-Error opening file : /Users/rakoon/Library/Containers/com.apple.Notes/Data/Library/Notes/NotesV7.storedata-wal
Traceback (most recent call last):
  File "/Users/rakoon/Documents/Projects/mac_apt/mac_apt/plugins/helpers/macinfo.py", line 1499, in Open
    file = MountedFile().open(mounted_path, 'rb')
  File "/Users/rakoon/Documents/Projects/mac_apt/mac_apt/plugins/helpers/macinfo.py", line 1267, in open
    self._file  = open(file_path, mode)
PermissionError: [Errno 1] Operation not permitted: '/Users/rakoon/Library/Containers/com.apple.Notes/Data/Library/Notes/NotesV7.storedata-wal'
MAIN-ERROR-An exception occurred while running plugin - NOTES
Traceback (most recent call last):
  File "/Users/rakoon/Documents/Projects/mac_apt/mac_apt/mac_apt.py", line 623, in <module>
    plugin.Plugin_Start(mac_info)
  File "/Users/rakoon/Documents/Projects/mac_apt/mac_apt/plugins/notes.py", line 432, in Plugin_Start
    ProcessNotesDbFromPath(mac_info, notes, source_path, user.user_name, 'V7')
  File "/Users/rakoon/Documents/Projects/mac_apt/mac_apt/plugins/notes.py", line 399, in ProcessNotesDbFromPath
    db, wrapper = OpenDbFromImage(mac_info, source_path, user)
  File "/Users/rakoon/Documents/Projects/mac_apt/mac_apt/plugins/notes.py", line 388, in OpenDbFromImage
    conn = sqlite.connect(inputPath)
  File "/Users/rakoon/Documents/Projects/mac_apt/mac_apt/plugins/helpers/macinfo.py", line 2402, in hooked
    if self._is_valid_sqlite_file(self.db_file_path_temp):
  File "/Users/rakoon/Documents/Projects/mac_apt/mac_apt/plugins/helpers/macinfo.py", line 2388, in _is_valid_sqlite_file
    with open (path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/rakoon/Documents/Projects/mac_apt/mac_apt/output/Temp433R/NotesV7.storedata'
MAIN-INFO---------------------------------------------------
MAIN-INFO-Finished in time = 00:00:00
MAIN-INFO-Review the Log file and report any ERRORs or EXCEPTIONS to the developers
```

and exported _`mac_apt.xlsx`_  is empty.
<img width="1723" alt="Screenshot 2023-07-21 at 8 25 19 PM" src="https://github.com/ydkhatri/mac_apt/assets/35058402/6254c542-89b4-444b-9f53-e5379cf308a2">

**Comment by ydkhatri** [comment]
OK, I know the problem. On last few versions of macOS, by default, it limits the files you can access even if they are in your own profile or even if you are Administrator. You need to enable **Full Disk** access to an application for this to work. Go to **System Settings** and enable it as shown below and that will fix it.

<img width="702" alt="Screenshot 2023-07-23 at 11 32 26 PM" src="https://github.com/ydkhatri/mac_apt/assets/13247440/2b9b9e4a-13ed-4a40-9685-75e0aa62fc96">

**Comment by qasimraheem** [comment]
thanks it worked

**Comment by qasimraheem** [comment]
thanks, it worked

**Comment by ydkhatri** [comment]
Great.
