### ISSUE TITLE
A1466 image with APFS is not processing

### ISSUE THREAD

**Issue by malashkevichandrei** [ydkhatri/mac_apt#14]
In my case an image with APFS volume cannot be processed by mac_apt. The following error will be seen:

```
$ python ~/mac_apt/mac_apt.py -o rep DD hard.raw ALL
Output path was : rep
MAIN-INFO-Started macOS Artifact Parsing Tool, version 0.3
MAIN-INFO-Dates and times are in UTC unless the specific artifact being parsed saves it as local time!
MAIN-INFO-Pytsk version = 20170801
MAIN-INFO-Pyewf version = 20140608
MAIN-INFO-Opened image hard.raw
MAIN-INFO-Looking at FS with volume label ''  @ offset 209735680
MAIN-INFO-Found an APFS container with uuid: B1F3F707-ED0B-49A6-B4DB-7439A47BB405
MAIN-INFO-Reading APFS volumes from container, this may take a few minutes ...
MAIN-ERROR-Error while reading APFS volumes
Traceback (most recent call last):
  File "/home/sansforensics/mac_apt/mac_apt.py", line 173, in FindOsxPartitionInApfsContainer
    mac_info.ReadApfsVolumes()
  File "/home/sansforensics/mac_apt/plugins/helpers/macinfo.py", line 844, in ReadApfsVolumes
    apfs_parser.read_volume_records()
  File "/home/sansforensics/mac_apt/plugins/helpers/apfs_reader.py", line 268, in read_volume_records
    self.read_entries(self.volume.root_block_num, root_block)
  File "/home/sansforensics/mac_apt/plugins/helpers/apfs_reader.py", line 352, in read_entries
    self.read_entries(entry.data.pointer, newblock)
  File "/home/sansforensics/mac_apt/plugins/helpers/apfs_reader.py", line 352, in read_entries
    self.read_entries(entry.data.pointer, newblock)
  File "/home/sansforensics/mac_apt/plugins/helpers/apfs_reader.py", line 355, in read_entries
    self.read_entries(entry.data.block_num.value, newblock)
  File "/home/sansforensics/mac_apt/plugins/helpers/apfs_reader.py", line 307, in read_entries
    if type(entry.data) == self.ptr_type: #apfs.Apfs.PointerRecord:
  File "/home/sansforensics/mac_apt/plugins/helpers/apfs.py", line 212, in data
    self._m_data = self._root.ExtattrRecord(self._io, self, self._root)
  File "/home/sansforensics/mac_apt/plugins/helpers/apfs.py", line 456, in __init__
    self.type_ea = self._root.EaType(self._io.read_u2le())
  File "/usr/local/lib/python2.7/dist-packages/enum/__init__.py", line 347, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python2.7/dist-packages/enum/__init__.py", line 662, in __new__
    raise ValueError("%s is not a valid %s" % (value, cls.__name__))
ValueError: 17 is not a valid EaType
MAIN.DISK_REPORT-INFO-Disk info
MAIN.DISK_REPORT-INFO-Disk Size   = 233.76 GB (251000193024 bytes)
MAIN.DISK_REPORT-INFO-Part Scheme = GPT
MAIN.DISK_REPORT-INFO-Block size  = 512 bytes
MAIN.DISK_REPORT-INFO-Num Sectors = 490234752.0 
MAIN-WARNING-:( Could not find a partition having an OSX installation on it
MAIN-INFO-Finished in time = 00:00:03
MAIN-INFO-Review the Log file and report any ERRORs or EXCEPTIONS to the developers
```

**Comment by ydkhatri** [comment]
Closing this for lack of response..
