### ISSUE TITLE
APFS Dirty volumes fail to process

### ISSUE THREAD

**Issue by ydkhatri** [ydkhatri/mac_apt#3]
If an APFS volume has not been cleanly unmounted, the resulting disk image cannot be processed by mac_apt. The following error will be seen:

```
MAIN-ERROR-Unknown error while trying to determine partition
MAIN-ERROR-Exception
Traceback (most recent call last):
  File "/Users/yogesh/Downloads/mac_apt_binaries_10.10/mac_apt.app/Contents/Resources/mac_apt.py", line 390, in <module>
  File "/Users/yogesh/Downloads/mac_apt_binaries_10.10/mac_apt.app/Contents/Resources/mac_apt.py", line 239, in FindOsxPartition
  File "/Users/yogesh/Downloads/mac_apt_binaries_10.10/mac_apt.app/Contents/Resources/mac_apt.py", line 177, in FindOsxPartitionInApfsContainer
  File "plugins/helpers/apfs_reader.pyc", line 669, in __init__
AttributeError: 'Node' object has no attribute 'root'
MAIN-WARNING-:( Could not find a partition having an OSX installation on it
```

**Comment by ydkhatri** [comment]
Need to figure out the right way to recover from a dirty volume. Not trivial, and will take time :(

**Comment by ydkhatri** [comment]
Fixed in the py3 branch, will move to master soon.
