### ISSUE TITLE
Error when using WIFI plugin

### ISSUE THREAD

**Issue by Banaanhangwagen** [ydkhatri/mac_apt#53]
I am using release v1.3.1.

When I try to parse an APFS image with WIFI-plugin, I get the following error:
```
MAIN-ERROR-An exception occurred while running plugin - WIFI
Traceback (most recent call last):
  File "C:\Github\mac_apt\mac_apt_compiled.py", line 671, in <module>
  File "plugins\airport_preferences.py", line 334, in Plugin_Start
  File "plugins\airport_preferences.py", line 268, in ParseWifiFromImage
  File "plugins\airport_preferences.py", line 289, in ReadKnownNetworksPlist
TypeError: '>' not supported between instances of 'datetime.datetime' and 'str'
```

For that reason, the output for WIFI stays empty.
I sent you the detailed DEBUG-log by e-mail.

**Comment by ydkhatri** [comment]
I haven't seen such a file, so if you have the file itself to share, I'd like to get that. 

In any case, I just made a quick fix for it. Let me know if it works for you.

**Comment by Banaanhangwagen** [comment]
The quick fix worked. Thank you
