### ISSUE TITLE
ios_apt: NameError: name 'ai' is not defined

### ISSUE THREAD

**Issue by Banaanhangwagen** [ydkhatri/mac_apt#61]
When executing ios_apt on a GK-dump, I get the following error:
```
Traceback (most recent call last):
  File "C:\github\mac_apt\ios_apt_compiled.py", line 191, in <module>
  File "plugins\helpers\macinfo.py", line 2106, in _GetAppDetails
NameError: name 'ai' is not defined
[19336] Failed to execute script ios_apt_compiled
MAIN.HELPERS.MACINFO-DEBUG-Exception while deleting temp files/folders: [WinError 32] The process cannot access the file because it is being used by another process: './TempNBJQ\\applicationState.db'
```

The complete DEBUG log is send to you by e-mail.
Thank you

**Comment by ydkhatri** [comment]
Ah, another silly bug. Fixed now. Uploading a new exe in a few minutes.

**Comment by ydkhatri** [comment]
v1.4.1 fixes this now.
