### ISSUE TITLE
TypeError occurs while reading APFS volumes

### ISSUE THREAD

**Issue by mnrkbys** [ydkhatri/mac_apt#69]
I've seen a TypeError in RecurseReadTree() like below, when I try to analyze a disk image (AFF4) that created with Cellebrite Digital Collector (former MacQuisition).

```
2021-09-01 16:55:38|MAIN|ERROR|Error while reading APFS volumes
Traceback (most recent call last):
  File "/Users/macforensics/Documents/GitHub/mac_apt/./mac_apt.py", line 307, in FindMacOsPartitionInApfsContainer
    mac_info.ReadApfsVolumes()
  File "/Users/macforensics/Documents/GitHub/mac_apt/plugins/helpers/macinfo.py", line 1079, in ReadApfsVolumes
    apfs_parser.read_volume_records()
  File "/Users/macforensics/Documents/GitHub/mac_apt/plugins/helpers/apfs_reader.py", line 424, in read_volume_records
    self.RecurseReadTree(self.volume.root_block_num, root_block, my_root, False, self.volume.root_tree_oid, 0, 0)
  File "/Users/macforensics/Documents/GitHub/mac_apt/plugins/helpers/apfs_reader.py", line 527, in RecurseReadTree
    self.RecurseReadTree(new_block_num, newblock, my_node, force_fstree, root_oid, oid, xid, debug_parent_list)
  File "/Users/macforensics/Documents/GitHub/mac_apt/plugins/helpers/apfs_reader.py", line 527, in RecurseReadTree
    self.RecurseReadTree(new_block_num, newblock, my_node, force_fstree, root_oid, oid, xid, debug_parent_list)
  File "/Users/macforensics/Documents/GitHub/mac_apt/plugins/helpers/apfs_reader.py", line 527, in RecurseReadTree
    self.RecurseReadTree(new_block_num, newblock, my_node, force_fstree, root_oid, oid, xid, debug_parent_list)
  File "/Users/macforensics/Documents/GitHub/mac_apt/plugins/helpers/apfs_reader.py", line 535, in RecurseReadTree
    location_oid = entry.data + (root_oid if no_blk_hdr_force_subtype_fstree else 0)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
2021-09-01 16:55:38|MAIN|ERROR|Error while trying to read partitions on disk
Traceback (most recent call last):
  File "/Users/macforensics/Documents/GitHub/mac_apt/./mac_apt.py", line 572, in <module>
    vol_info = pytsk3.Volume_Info(img)
OSError: Volume_Info_Con: (tsk3.c:662) Error opening Volume_Info: Cannot determine partition type
```

Also, attaching a log file.
[Log.20210901-165503.txt](https://github.com/ydkhatri/mac_apt/files/7089441/Log.20210901-165503.txt)

**Comment by ydkhatri** [comment]
Can you quickly test with the following and tell me if that fixes it? 
In plugins/helpers/apfs.py, line 432, add value 7 as below.
![image](https://user-images.githubusercontent.com/13247440/131656483-dc02af2c-4934-4cd1-a2a3-1e0309c1211e.png)

**Comment by mnrkbys** [comment]
Thanks for a quick response, @ydkhatri .
I modified it, and it appears to be working fine.
Although, There is a parser error in the SPOTLIGHT plugin. I will submit a new issue.

**Comment by ydkhatri** [comment]
Yes, Apple has changed some stufff in spotlight it seems, as I've seen some parsing problems too. I should take a look later this week. 
For now, https://github.com/ydkhatri/mac_apt/commit/f55f3b19d886a9fa83a4371eed7af93e7596788f fixes the apfs parsing issue. We don't process the crypto_state leaf nodes, I added it to the code to bypass.

**Comment by ydkhatri** [comment]
#

**Comment by ydkhatri** [comment]
Apparently the spotlight issues I was seeing were related to an HFS extent reading bug when reading from HFS archives (ones created by macosac). I've fixed that, please create a new issue if you still have problems with spotlight parsing.
