### ISSUE TITLE
Spotlight parser error

### ISSUE THREAD

**Issue by mnrkbys** [ydkhatri/mac_apt#72]
I've seen another spotlight plugin's parser error like below:
```
2021-09-05 21:47:02|MAIN.SPOTLIGHT.SPOTLIGHT_PARSER|ERROR|Error trying to process item @ block 9D014 offset 0
Traceback (most recent call last):
  File "/Users/macforensics/Documents/GitHub/forked/mac_apt/plugins/helpers/spotlight_parser.py", line 830, in ParseMetadataBlocks
    md_item.ParseItem(self.properties, self.categories, self.indexes_1, self.indexes_2)
  File "/Users/macforensics/Documents/GitHub/forked/mac_apt/plugins/helpers/spotlight_parser.py", line 292, in ParseItem
    singles = [self.ReadSingleByte() for x in range(num_values)]
  File "/Users/macforensics/Documents/GitHub/forked/mac_apt/plugins/helpers/spotlight_parser.py", line 292, in <listcomp>
    singles = [self.ReadSingleByte() for x in range(num_values)]
  File "/Users/macforensics/Documents/GitHub/forked/mac_apt/plugins/helpers/spotlight_parser.py", line 151, in ReadSingleByte
    single = struct.unpack("<B", self.data[self.pos : self.pos + 1])[0]
struct.error: unpack requires a buffer of 1 bytes
2021-09-05 21:47:21|MAIN.SPOTLIGHT.SPOTLIGHT_PARSER|ERROR|Error, cannot proceed, invalid property index 331, skip=68
2021-09-05 21:47:21|MAIN.SPOTLIGHT.SPOTLIGHT_PARSER|ERROR|Error trying to process item @ block 2285014 offset 17300
Traceback (most recent call last):
  File "/Users/macforensics/Documents/GitHub/forked/mac_apt/plugins/helpers/spotlight_parser.py", line 830, in ParseMetadataBlocks
    md_item.ParseItem(self.properties, self.categories, self.indexes_1, self.indexes_2)
  File "/Users/macforensics/Documents/GitHub/forked/mac_apt/plugins/helpers/spotlight_parser.py", line 327, in ParseItem
    value = self.ReadDate()
  File "/Users/macforensics/Documents/GitHub/forked/mac_apt/plugins/helpers/spotlight_parser.py", line 102, in ReadDate
    mac_abs_time = struct.unpack("<q", struct.pack("<Q", int(mac_abs_time)) )[0] # double to signed int64
struct.error: argument out of range
```

The archive file is AFF4 that was created with Cellebrite Digital Collector.
Also, attaching the log file.
[Log.20210905-213434.txt](https://github.com/ydkhatri/mac_apt/files/7111762/Log.20210905-213434.txt)

I can also provide the spotlight files for you.

**Comment by ydkhatri** [comment]
Yes, please provide the spotlight files for me to debug.

**Comment by mnrkbys** [comment]
I've sent a DM on Twitter to share the spotlight files.

**Comment by ydkhatri** [comment]
I've fixed some problems with prop_type 0x8, which I think fixes this issue.  Can you check and confirm?

**Comment by mnrkbys** [comment]
Thank you for fixing it!
It now works without errors.
